In [1]:
import numpy as np

In [2]:
# array manupulation
arr = np.random.randint(1,10, (3,4))
arr

array([[3, 7, 6, 6],
       [1, 9, 1, 4],
       [1, 9, 5, 4]])

In [5]:
arr.reshape((6,2))

array([[3, 7],
       [6, 6],
       [1, 9],
       [1, 4],
       [1, 9],
       [5, 4]])

In [6]:
arr.T

array([[3, 1, 1],
       [7, 9, 9],
       [6, 1, 5],
       [6, 4, 4]])

In [8]:
arr.flatten()

array([3, 7, 6, 6, 1, 9, 1, 4, 1, 9, 5, 4])

In [9]:
arr1 = np.array([1,2,3,4,5])
arr1.ndim

1

In [10]:
np.expand_dims(arr1, axis = 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
arr

array([[3, 7, 6, 6],
       [1, 9, 1, 4],
       [1, 9, 5, 4]])

In [12]:
np.squeeze(arr)

array([[3, 7, 6, 6],
       [1, 9, 1, 4],
       [1, 9, 5, 4]])

In [13]:
data = np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [14]:
np.squeeze(data)

array([1, 2, 3])

In [15]:
arr1

array([1, 2, 3, 4, 5])

In [16]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [22]:
np.roll(arr1, 1)

array([5, 1, 2, 3, 4])

In [23]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [26]:
# Numpy binary operation

arr1 = np.random.randint(1,10, (3,4))
arr1

array([[4, 3, 9, 2],
       [9, 9, 5, 1],
       [7, 2, 7, 5]])

In [27]:
arr2 = np.random.randint(1,10, (3,4))
arr2

array([[1, 1, 9, 2],
       [9, 8, 9, 6],
       [1, 7, 6, 9]])

In [28]:
arr1 + arr2

array([[ 5,  4, 18,  4],
       [18, 17, 14,  7],
       [ 8,  9, 13, 14]])

In [29]:
arr1 * arr2

array([[ 4,  3, 81,  4],
       [81, 72, 45,  6],
       [ 7, 14, 42, 45]])

In [31]:
arr1 & arr2

array([[0, 1, 9, 2],
       [9, 8, 1, 0],
       [1, 2, 6, 1]])

In [32]:
arr1 > arr2

array([[ True,  True, False, False],
       [False,  True, False, False],
       [ True, False,  True, False]])

In [33]:
# Numpy - String function
arr = np.array(['dinesh', 'kokare'])
arr



array(['dinesh', 'kokare'], dtype='<U6')

In [34]:
np.char.upper(arr)

array(['DINESH', 'KOKARE'], dtype='<U6')

In [35]:
np.char.title(arr)

array(['Dinesh', 'Kokare'], dtype='<U6')

In [36]:
# Numpy - Mathematical function
arr1


array([[4, 3, 9, 2],
       [9, 9, 5, 1],
       [7, 2, 7, 5]])

In [38]:
np.sin(arr1)

array([[-0.7568025 ,  0.14112001,  0.41211849,  0.90929743],
       [ 0.41211849,  0.41211849, -0.95892427,  0.84147098],
       [ 0.6569866 ,  0.90929743,  0.6569866 , -0.95892427]])

In [39]:
np.cos(arr1)

array([[-0.65364362, -0.9899925 , -0.91113026, -0.41614684],
       [-0.91113026, -0.91113026,  0.28366219,  0.54030231],
       [ 0.75390225, -0.41614684,  0.75390225,  0.28366219]])

In [40]:
np.log10(arr1)

array([[0.60205999, 0.47712125, 0.95424251, 0.30103   ],
       [0.95424251, 0.95424251, 0.69897   , 0.        ],
       [0.84509804, 0.30103   , 0.84509804, 0.69897   ]])

In [41]:
np.mean(arr1)

5.25

In [2]:
import numpy as np

# sort, search and counting functions
arr = np.array([1,2,6, 7, 3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
np.sort(arr)

array([1, 2, 3, 4, 5])

In [4]:
np.searchsorted(arr, 32)

5

In [6]:
arr1 =np.array([0,354,45,32,17])
arr1

array([  0, 354,  45,  32,  17])

In [7]:
np.count_nonzero(arr1)

4

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
np.where(arr > 2)

(array([2, 3, 4], dtype=int64),)

In [10]:
np.extract (arr>2, arr)

array([3, 4, 5])

In [11]:
# numpy - bite swapping
arr

array([1, 2, 3, 4, 5])

In [13]:
arr.byteswap()

array([16777216, 33554432, 50331648, 67108864, 83886080])

In [14]:
# Numpy - copies and view
arr

array([1, 2, 3, 4, 5])

In [16]:
a = np.copy(arr)
a

array([1, 2, 3, 4, 5])

In [18]:
b = arr.view()
b

array([1, 2, 3, 4, 5])

In [19]:
arr

array([1, 2, 3, 4, 5])

In [21]:
b[0] = 67

In [22]:
b

array([67,  2,  3,  4,  5])

In [23]:
arr

array([67,  2,  3,  4,  5])

In [24]:
# numpy - matrix library
import numpy.matlib as nm

In [26]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [29]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [36]:
# Numpy - linear algebra
arr1 = np.random.randint([[2,3], [4,5]])
arr1




array([[1, 1],
       [2, 2]])

In [37]:
arr2 = np.random.randint([[5,3], [2,5]])
arr2

array([[3, 2],
       [1, 1]])

In [38]:
np.dot(arr1,arr2)

array([[4, 3],
       [8, 6]])

In [39]:
arr1@arr2

array([[4, 3],
       [8, 6]])

In [40]:
np.concatenate(arr1, arr2)

TypeError: only integer scalar arrays can be converted to a scalar index