In [4]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

- Yes, there is a difference between both lists. list_ data type is python list whereas the data type of array_list is numpy.ndarray. Please refer below code to print the data types of both variables

In [5]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [6]:
# understand the data type of elements in list_
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [7]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list: will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_and arra_list.

In [8]:
array_list = np.array(object = list_, dtype = int)

In [9]:
type(array_list)

numpy.ndarray

- The data type of elements in both variables list_ and array_list will remain the same even after making changes to array_list. This is because the data type of elements in a NumPy array is determined by the data type of the input data when creating the array, and it remains consistent throughout the array.

In [11]:
# data type in list
for i in list_:
    print(type(i))

# data type in array_list
for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [12]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [13]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [14]:
# find shape
np.shape(num_array)

(2, 3)

In [15]:
# find size
np.size(num_array)

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [16]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# check size
np.size(arr)

9

In [18]:
# check shape
np.shape(arr)

(3, 3)

### Q6. Create an identity matrix of shape (5,5) using numpy functions? 

In [19]:
arr1 = np.random.randint(1,10, (5,5))
arr1

array([[2, 1, 7, 7, 5],
       [2, 9, 4, 2, 2],
       [6, 5, 1, 6, 3],
       [9, 1, 3, 6, 5],
       [6, 4, 9, 4, 3]])

In [21]:
np.shape(arr1)

(5, 5)