In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
# convert it into array
ar = np.array(l)

In [5]:
# one dimentional array
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [8]:
# two dimentional array
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
a = [2,3,4]

In [11]:
np.asarray(a)

array([2, 3, 4])

In [13]:
# matrix is subset of array
b = np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [16]:
a = np.array(l)
a

array([1, 2, 3, 4])

In [17]:
c = a

In [18]:
c

array([1, 2, 3, 4])

In [19]:
a

array([1, 2, 3, 4])

In [20]:
c[0]

1

In [21]:
c[0] = 100
c

array([100,   2,   3,   4])

In [22]:
a

array([100,   2,   3,   4])

In [24]:
d = np.copy(a)
d

array([100,   2,   3,   4])

In [25]:
a[1] = 400
a

array([100, 400,   3,   4])

In [26]:
d

array([100,   2,   3,   4])

In [28]:
np.fromfunction(lambda i, j : i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i, j : i * j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [32]:
iterable = (i * i for i in range(5))
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [35]:
np.fromstring('123 123', sep = " ")

array([123., 123.])

In [37]:
np.fromstring('234, 234', sep = ",")

array([234., 234.])

In [39]:
# Numpy data types
l = [1,2,3,4]
ar = np.array(l)
ar

array([1, 2, 3, 4])

In [40]:
# shape
ar.ndim

1

In [42]:
ar2 = np.array([[1,2,3], [4,5,6]])
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
ar2.ndim

2

In [45]:
# size
ar2.size

6

In [46]:
# shape
ar2.shape

(2, 3)

In [48]:
ar.dtype

dtype('int32')

In [49]:
ar22 = np.array([[1.4,45,45],[23,45,66]])
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [50]:
ar22.dtype

dtype('float64')

In [51]:
list(range(5))

[0, 1, 2, 3, 4]

In [52]:
np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [53]:
np.arange(2.3, 5.6, 0.5)

array([2.3, 2.8, 3.3, 3.8, 4.3, 4.8, 5.3])

In [54]:
# convert it into list
list(np.arange(2.3, 5.6, 0.5))

[2.3, 2.8, 3.3, 3.8, 4.3, 4.8, 5.3]

In [58]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [59]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
on = np.ones((2,3,2))
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [66]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [68]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [69]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [70]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [73]:
arr = np.random.randn(3,4)

In [74]:
import pandas as pd
pd.DataFrame(arr)

0         1         2         3
0 -0.023991  0.183692  0.904322 -0.272964
1  0.497738  1.671852 -0.961273  0.947641
2 -0.968936  0.535514  0.263740  0.625392

In [79]:
arr = np.random.rand(3,4)
arr

array([[0.17987116, 0.51678582, 0.80269008, 0.27082217],
       [0.52971665, 0.72257513, 0.79374763, 0.2479923 ],
       [0.07315437, 0.69918154, 0.72146662, 0.18670618]])

In [77]:
np.random.randint(1,110,(3,4))

array([[ 52,  72,  77,   5],
       [102,  65, 102,  95],
       [ 31,  30,  26,  91]])

In [80]:
arr.reshape(6,2)

array([[0.17987116, 0.51678582],
       [0.80269008, 0.27082217],
       [0.52971665, 0.72257513],
       [0.79374763, 0.2479923 ],
       [0.07315437, 0.69918154],
       [0.72146662, 0.18670618]])